### ISSUE TITLE
Redeploy Clusters to SDN Compartment (Cloud Zone)

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#185]
The target network environment for the OpenShift 4 clusters is the new **SDN Compartment**.  All clusters will need to be re-deployed as SDN compartment tenants.

This Epic is to track both the pre-requisite tasks before we can begin re-deployment, as well as the individual cluster re-deployments.

This Epic will be complete when all clusters have been successfully deployed as SDN Compartment tenants.

*Can remove/replace step with dependent tasks as we define new tasks.*

High Level Steps (to be verified)
Tracked in Issue #175
- [x] Meeting yesterday with A&E to discuss the implementation design
- [x] Confirm the routing path purposed from the WAN router to the F5s will work (Stuart)
- [x] Create diagrams of network objects and traffic flows in the SDN compartment (Scott)
- [x] Create a Brief Note on the use of  the F5s in the OCP environment (Scott)

- [x] Present to Brief Note to JTSAWG and JOC (OCIO Hosting Services) for approval (Scott)

Tracked in Issue #174
- [x] Discuss our specific SDN solution with ISS, to determine how it fits into the SDN Compartment pattern. Document this in a tech note for JTSAWG approval. Use this to document for obtaining STRA (AS, ISS)
- [x] Create a tech note documenting how the 

Not Tracked yet?
- [x] Stand up fresh F5 VCMP or virtuals and perform base configuration (AS/ATT)
- [x] Update SiS Firewall rules as needed (443 and 6443) (Steven to request)
- [x] Request new public subnets and private subnets (Steven)
- [x] Configure the F5 BIG-IP to work with the F5 Container Ingress Services(AS/ATT)
- [x] Set up API VIPs on new F5s (AS/ATT)
- [x] Move VMs into new subnets (Dan/Steven)
- [x] Rebuild cluster and test

Target date: End of Sprint 7

**Comment by mitovskaol** [comment]
@stregear can you please update the checklist in the ticket where the tasks have been complete. Thanks!

**Comment by tosazuwa** [comment]
Worked with Sharon to check off complete tasks
Sharon Submitted a request to IIS waiting to confirm if an STRA is required.

**Comment by mitovskaol** [comment]
@tosazuwa FYI @NickCorcoran is working on the OCP 4 STRA at the moment.
