### ISSUE TITLE
Aqua Automation for OCP

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/OpenShift4-RollOut#196]
Update Automation for deploying Aqua on OCP4

- [ ] Upgrade to the latest version of Aqua (4.6)
- [ ] Ensure Active High-Availability for Aqua Console -- Not Passive
- [ ] Configure backups
- [ ] Discuss plan for post launch aqua configuration automation

**Comment by mitovskaol** [comment]
@patricksimonian  Is this still relevant?

**Comment by j-pye** [comment]
@mitovskaol still relevant but we could probably close this one in favor of some more specific tasks on the developer-experience board?
