### ISSUE TITLE
Set Up Silver Cluster Hardware

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#209]
- [x] Datacenter provider upgrade rack power #210
- [x] Rack ToR Switches #163 to order them
- [x] Rack NAS Switches #163 to order them
- [x] Rack servers - Delivery expected May 22
- [x] Rack NetApp
- [x] Set up DNS for hosts
- [ ] Add iLOs to OneView

**Comment by stregear** [comment]
TOR and NAS switches for the silver cluster are still with procurement and finance, so  a PO has not yet been cut expect this will take another week and a half  to get a PO out of the door.
Switches: Once switches arrive, will take DCM approx 4 hours to rack and cable each switch;   Network team will need another 4 hours per  switch to assign IP addresses, names etc. and load the configuration.

**Comment by stregear** [comment]
If the servers arrive May 22, they should be completely racked by the end of next week  May 29th.   The 1GB management switches we have in stock and those 2 connections per server can be cabled.   The remaining cabling (60 cables) cannot be completed until the switches arrive.  DCM will manually configure the iLOs , however,  this will require  DNS assignments and the iLO IP which typically takes about a week.

NetApp will be racked by end of next week as well.    

Have two HP 5900 (NAS) switches in stock - a request has gone into DXC network to get the switches built/configured  so the servers and the NetApp will be able to talk to each other.

**Comment by stregear** [comment]
Time (aprox) : 

1 week an 2 days to rack servers/NetApp (cabling when the switches finally arrive may take another 3-4 days) and it will take 4 hrs to rack and cable each switch plus 4 hrs to build each switch.
2 days to rack/cable and configure the temporary HP NAS switches.
2-3 weeks to configure the NetApp.
2- 3 weeks to build a cluster and 2 - 3  week to burn it in and test.
F5 /SDN - a month and half.

**Comment by Joe-Craig** [comment]
I was just given dates for completing the electrical energizing of the 3 new racks.

CHG0034704 K147 - Branch Circuit Maintenance - YELLOW on 6/25/20
CHG0034696 K147 - Branch Circuit Maintenance - RED on 6/21/20
CHG0034705 K147 - Branch Circuit Maintenance – BLUE on  6/18/20

With the latest date being June 25th, that is the first date where all racks will have full power diversity.
Each rack will have at least 1 PDU operational as of June 21st

**Comment by StevenBarre** [comment]
iLOs configured by hand for now. Some DNS set up, but some still to do.

Completed first test install of OCP to confirm basics of the hardware and networking are functional.

**Comment by StevenBarre** [comment]
Complete!
