### ISSUE TITLE
Penetration test for new cluster

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/OpenShift4-RollOut#231]
- [x] Create SoW
- [x] Agree on vendor/procurement w/ OCIO ISB
- [x] Agree on scope and reporting w/ OCIO ISB
- [ ] Schedule testing
- [ ] Remediate issues
- [ ] Retest remediated issues
