### ISSUE TITLE
Aporeto on OCP4

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/OpenShift4-RollOut#251]
Definition of Done:
Aporeto is ready to install on any cluster with the following requirements:
- [x] Playbooks support the install, upgrade, and install of Aporeto
- [x] Host Protection Enabled and Configured
- [x] Enforcer covers all nodes
- [x] OCP can be upgraded without needing to disable Aporeto
- [ ] Protective measures in case of Aporeto Failure have been put in place
-  [ ] Update Aporeto Developer Documentation

**Comment by jleach** [comment]
This EPIC is no longer needed. Aporeto was installed and then removed from the cluster(s).
