### ISSUE TITLE
Migrate Developer SSO to OCP4

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#269]
Migration of existing SSO to OCP4 will need several steps:

- [ ] Deploy sandbox SSO in OCP4
- [ ] Change SSO endpoints from {x}.pathfinder.gov.bc.ca -> {x}.oidc.gov.bc.ca
- [ ] Create dev/test/prod deployment pipeline for OCP4
- [ ] State migration steps/plans
- [ ] Shutdown pathfinder deployed SSO instances

Definition of Done:
Platform Services SSO migration to the silver cluster is complete, with legacy (pathfinder) deployments offline.

**Comment by ShellyXueHan** [comment]
Update for Step 1 - Deploy sandbox SSO in OCP4:
- successfully imported image
- tested out a brand new deployment of SSO in ARO
- Blocker: patroni deployment does not work yet (Shea is currently troubleshooting this, either that we fix the current template or switch to operator)

**Comment by ShellyXueHan** [comment]
Update for Step 2 - Change SSO endpoints from {x}.pathfinder.gov.bc.ca -> {x}.oidc.gov.bc.ca:
- enabled new service name in dev instance, so far so good
- continue on to test and prod:
(tickets in another zenhub board)
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/597
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/598
