### ISSUE TITLE
Vault MVP on OCP4

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/OpenShift4-RollOut#276]
Description:
The Vault Minimum Viable Product on the new OpenShift 4 platform comprises the following elements:
- HA Deployment in an OpenShift cluster
- Developer accessible service as an alternative to OpenShift secrets

Definition of Done:
- [X] Vault HA Deployment within a single cluster
- [ ] Vault Architecture Design Finalized and Documented
- [X] Vault Structure Design Documented
- [X] Provisioning method for Vault consumers Documented
- [ ] Provisioning method for Vault consumers implemented
- [ ] Vault Developer Documentation

**Comment by manderson-it** [comment]
@j-pye and I have updated the description and definition of done. We decided to remove the Vault DR replication from the MVP as it is currently blocked and tracked in the issue here [#318](https://app.zenhub.com/workspace/o/bcdevops/openshift4-rollout/issues/318).

**Comment by mitovskaol** [comment]
This work is tracked in a different ticket.
