### ISSUE TITLE
Project Provisioning

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/OpenShift4-RollOut#281]
**Describe the issue**
Reminder - add estimate to ticket (based on level complexity, effort, risk etc.)

**Which Sprint Goal is this issue related to?**
The 'Milestone' should clearly list Sprint Goals - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done Checklist (where applicable)**
- [ ]  Ticket merged to master or story branch
- [ ]  Add PR numbers - If available
- [ ] All tests passed (specify what kind of testing is done)
- [ ] Developer to list Config changes/ Update documents and designs
- [ ] Design / Solution accepted by Product Owner
- [ ] Acceptance criteria has been defined (happy path, known sad paths)
- [ ] Test coverage acceptable (LAB & PROD)
- [ ] Peer Reviewed
- [ ] PR Accepted

**Comment by mitovskaol** [comment]
Project provisioning for Openshift 4 has been implemented in Project Registry
