### ISSUE TITLE
Artifactory Service Deployment

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#293]
**Describe the issue**
Artifactory deployed to Lab and Silver clusters with the following features:
- [x] Caching image repository for all external images
- [x] Automation for provisioning private repositories and Artifactory access (Via operator)

**Which Sprint Goal is this issue related to?**

**Additional context**
Artifactory service already exists with appropriate features/functionality.  Additional documentation is required to aid development team consumption of this service.

**Definition of done Checklist (where applicable)**
- [x] Artifactory deployed to klab cluster with a resilient deployment
- [x] Artifactory deployed to Silver Cluster with a resilient deployment
- [x] ArtifactoryOperator deployed to silver cluster
- [x] Developer usage documentation available in DevHub
- [x] Operational documentation created that includes: deployment architecture, backup, recovery, upgrade
- [ ] Functional testing of the following:
  - [x] operator provisioning artifactory access to namespaces.
  - [ ] operator provisioning of private artifact repository
  - [x] Pull through/caching feature confirmed to work as documented in Developer documentation (docker images?)
  - [ ] Repository push/pull verified for private repository
  - [ ] Private repository access changes tested (following developer instructions to add/remove access for additional artifactory service accounts for a private repository)

• Design / Solution accepted by Product Owner
• Acceptance criteria has been defined (happy path, known sad paths)
• Test coverage acceptable (LAB & PROD)
• Peer Reviewed

**Comment by caggles** [comment]
Closing this because we have two major epics dealing with the artifactory stuff, and I'm moving all of this into one.

**Comment by jefkel** [comment]
@caggles please update with links to duplicate tickets/requirements.  This was a large ticket with multiple requirements - have all of the included requirements been identified in duplicated tickets? (mapping would be great)
