### ISSUE TITLE
SG - OCP 4- Cluster Configuration Management MVP

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/OpenShift4-RollOut#320]
As a part of the OCP4 Rollout we need a way to manage our many clusters. To do this we have chosen to use a GitOps approach.

Tools:
- ArgoCD - GitOps
- Github Actions - CCM Generation
- Github App - CCM GitOps CI
- Sealed Secrets - Store Encrypted K8s Secrets in git

Definition of Done:
- [x] Document GitOps Flow and Git Repository Structure
- [x] Implement CCM Generation Workflow 
- [x] Implement CCM Tools into CCM (Use GitOps to manage the CCM Tools)

Clusters:
- [x] Implement Base CCM Workflow for KLAB
- [x] Implement Base CCM Workflow for CLAB
- [x] Implement Base CCM Workflow for Silver

**Comment by j-pye** [comment]
Additional Private Repositories have been requested for Cluster Specific Config Files
https://github.com/BCDevOps/devops-requests/issues/489
