### ISSUE TITLE
ARO Pathfinder Build

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#335]
**Describe the issue**
The JAG team would like to test out some deployments in ARO. Due to the fact that the platform-services cluster will be a bit volatile and should be dedicated to platform-services tools, we need to buid a new ARO pathfinder cluster and create namespaces for the JAG team. 

**Which Sprint Goal is this issue related to?**
ARO and Pathfinder Deployment. 

**Definition of done Checklist (where applicable)**
- [x] ARO Pathfinder Cluster Built #327
- [ ] ARO Pathfinder Onboarded into Argo config management #328
- [ ] ARO Pathfinder Storage Classes Created #329
- [ ] ARO Pathfinder SSO Integration Completed #330
- [ ] ARO Pathfinder Project Provisioning for auth users disabled #331
- [ ] ARO Pathfinder SSL Certificates Installed  #332
- [ ] ARO Pathfinder JAG Namespaces Created #333 
- [ ] ARO Pathfinder basic orientation for JAG #334
